### ISSUE TITLE
[Bug] Callback function in button didn't executed

### ISSUE THREAD

**Issue by nekolyst** [1pxlchibs/PXLUI#1]
The callback function in the pxlui_button(...,function()) didn't executed when click LMB or trigger select key.

After some investigation, I found it has event execute order issue on pPXLUIElement and oPXLUICursor.
The id.hover set to false first on BeginStep event in the pPXLUIElement. It should be evaluated on Step event in oPXLUICursor, and on Step event in pPXLUIElement later. But currently Step in the pPXLUIElement was executed earlier than oPXLUICursor. So id.hover was never be true when run Step event in the oPXLUIButton.

In this moment, I just temporarily change pPXLUIElement's Step event to EndStep to avoid this issue. Not sure if cause other issues.

**Comment by 1pxlchibs** [comment]
Closed the issue, as new version is out which should address this issue.
